### ISSUE TITLE
Failed to load API definition.

### ISSUE THREAD

**Issue by mayder** [yii2mod/yii2-swagger#15]
`Errors

Fetch errorInternal Server Error /inspecao/aplicacao/web/swagger/json-schema`

2021-05-17 23:31:55 [::1][4][to85286h8jkkjf1oh09v5uqlln][error][yii\base\ErrorException:1024] yii\base\ErrorException: Required @SWG\Info() not found in D:\www\inspecao\aplicacao\vendor\zircote\swagger-php\src\Logger.php:38
Stack trace:
#0 D:\www\inspecao\aplicacao\vendor\zircote\swagger-php\src\Logger.php(38): yii\web\ErrorHandler->handleError()
#1 D:\www\inspecao\aplicacao\vendor\zircote\swagger-php\src\Logger.php(38): ::trigger_error()
#2 D:\www\inspecao\aplicacao\vendor\zircote\swagger-php\src\Logger.php(68): Swagger\Logger->Swagger\{closure:D:\www\inspecao\aplicacao\vendor\zircote\swagger-php\src\Logger.php:34-39}()
#3 D:\www\inspecao\aplicacao\vendor\zircote\swagger-php\src\Logger.php(68): ::call_user_func:{D:\www\inspecao\aplicacao\vendor\zircote\swagger-php\src\Logger.php:68}()
#4 D:\www\inspecao\aplicacao\vendor\zircote\swagger-php\src\Annotations\AbstractAnnotation.php(388): Swagger\Logger::notice()
#5 D:\www\inspecao\aplicacao\vendor\zircote\swagger-php\src\Annotations\Swagger.php(150): Swagger\Annotations\Swagger->validate()
#6 D:\www\inspecao\aplicacao\vendor\zircote\swagger-php\src\Analysis.php(331): Swagger\Annotations\Swagger->validate()
#7 D:\www\inspecao\aplicacao\vendor\zircote\swagger-php\src\functions.php(56): Swagger\Analysis->validate()
#8 D:\www\inspecao\aplicacao\vendor\yii2mod\yii2-swagger\OpenAPIRenderer.php(85): ::Swagger\scan()
#9 D:\www\inspecao\aplicacao\vendor\yiisoft\yii2\caching\Cache.php(597): yii2mod\swagger\OpenAPIRenderer->yii2mod\swagger\{closure:D:\www\inspecao\aplicacao\vendor\yii2mod\yii2-swagger\OpenAPIRenderer.php:84-86}()
#10 D:\www\inspecao\aplicacao\vendor\yiisoft\yii2\caching\Cache.php(597): ::call_user_func:{D:\www\inspecao\aplicacao\vendor\yiisoft\yii2\caching\Cache.php:597}()
#11 D:\www\inspecao\aplicacao\vendor\yii2mod\yii2-swagger\OpenAPIRenderer.php(86): yii\caching\FileCache->getOrSet()
#12 D:\www\inspecao\aplicacao\vendor\yii2mod\yii2-swagger\OpenAPIRenderer.php(70): yii2mod\swagger\OpenAPIRenderer->getSwaggerDocumentation()
#13 D:\www\inspecao\aplicacao\vendor\yiisoft\yii2\base\Action.php(94): yii2mod\swagger\OpenAPIRenderer->run()
#14 D:\www\inspecao\aplicacao\vendor\yiisoft\yii2\base\Action.php(94): ::call_user_func_array:{D:\www\inspecao\aplicacao\vendor\yiisoft\yii2\base\Action.php:94}()
#15 D:\www\inspecao\aplicacao\vendor\yiisoft\yii2\base\Controller.php(181): yii2mod\swagger\OpenAPIRenderer->runWithParams()
#16 D:\www\inspecao\aplicacao\vendor\yiisoft\yii2\base\Module.php(534): app\controllers\SwaggerController->runAction()
#17 D:\www\inspecao\aplicacao\vendor\yiisoft\yii2\web\Application.php(104): yii\web\Application->runAction()
#18 D:\www\inspecao\aplicacao\vendor\yiisoft\yii2\base\Application.php(392): yii\web\Application->handleRequest()
#19 D:\www\inspecao\aplicacao\web\index.php(14): yii\web\Application->run()
#20 {main}

**Comment by fejan-malek** [comment]
Hey there this helped me

https://stackoverflow.com/questions/32884345/required-swg-info-not-found
